language: node_js
node_js:
  - "8"
sudo: enabled
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
script: yarn run build
